MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Models/Siniflar/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Personel
    {
        [Key]
        public int PersonelId { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelAd { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30)]
        public string PersonelSoyad { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(250)]
        public string PersonelGorsel { get; set; }

        public ICollection<SatisHareket> SatisHarekets { get; set; }

        public Departman Departman { get; set; }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel

        Context c = new Context();
        public ActionResult PersonelListele()
        {
            var personelList = c.Personels.ToList();
            return View(personelList);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> degerler = (from x in c.Departmans.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.DepartmanAd,
                                                 Value = x.DepartmanId.ToString()
                                             }).ToList();
            ViewBag.dgr1 = degerler;
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(Personel personel)
        {
            c.Personels.Add(personel);
            c.SaveChanges();
            return RedirectToAction("PersonelListele");
        }

        public ActionResult PersonelGetir(int id)
        {
            var per = c.Personels.Find(id);
            List<SelectListItem> degerler = (from x in c.Departmans.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.DepartmanAd,
                                                 Value = x.DepartmanId.ToString()
                                             }).ToList();
            ViewBag.dgr1 = degerler;
            return View(per);
        }

        public ActionResult PersonelGuncelle(Personel personel)
        {
            var per = c.Personels.Find(personel.PersonelId);
            per.PersonelAd = personel.PersonelAd;
            per.PersonelSoyad = personel.PersonelSoyad;
            per.PersonelGorsel = personel.PersonelGorsel;
            per.DepartmanId = personel.DepartmanId;
            c.SaveChanges();
            return RedirectToAction("PersonelListele");
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Personel Ekle</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd, "Personel Adı")
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad, "Personel Soyadı")
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel, "Personel Görsel")
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman, "Departman")
    @Html.DropDownListFor(x => x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Kaydet</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Personel Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    @Html.HiddenFor(x => x.PersonelId)
    @Html.LabelFor(x => x.PersonelAd, "Personel Adı")
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad, "Personel Soyad")
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel, "Personel Görsel")
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Departman, "Personel Departman")
    @Html.DropDownListFor(x => x.DepartmanId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Güncelle</button>
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Personel/PersonelListele.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "PersonelListele";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-striped">
    <tr>
        <th>Personel Id</th>
        <th>Personel Ad</th>
        <th>Personel Soyad</th>
        <th>Personel Görsel</th>
        <th>Departman</th>
        <th>Güncelle</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.PersonelId</td>
            <td>@item.PersonelAd</td>
            <td>@item.PersonelSoyad</td>
            <td>@item.PersonelGorsel</td>
            <td>@item.Departman.DepartmanAd</td>
            <td><a href="/Personel/PersonelGetir/@item.PersonelId" class="btn btn-warning">Güncelle</a></td>          
            <td><a href="/Departman/DepartmanPersonelSatis/@item.PersonelId" class="btn btn-secondary">Satış Geçmişi</a></td>
        </tr>
    }
</table>

<a href="/Personel/PersonelEkle" class="btn btn-primary">Ekle</a>