MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using MvcOnlineTicariOtomasyon.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis

        Context c = new Context();
        public ActionResult SatisListele()
        {
            var satisList = c.satisHarekets.ToList();
            return View(satisList);
        }

        [HttpGet]
        public ActionResult SatisEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunId.ToString()
                                           }).ToList();

            List<SelectListItem> deger2 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariId.ToString()
                                           }).ToList();

            List<SelectListItem> deger3 = (from x in c.Personels.ToList() 
                                           select new SelectListItem 
                                           { 
                                               Text = x.PersonelAd + " " + x.PersonelSoyad, 
                                               Value = x.PersonelId.ToString()
                                           }).ToList();

            ViewBag.dgr1 = deger1;
            ViewBag.dgr2 = deger2;
            ViewBag.dgr3 = deger3;
            return View();
        }

        [HttpPost]
        public ActionResult SatisEkle(SatisHareket satisHareket)
        {
            satisHareket.Tarih = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            c.satisHarekets.Add(satisHareket);
            c.SaveChanges();
            return RedirectToAction("SatisListele");
        }
    }
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Satış Detay</h2>
<br />
<table class="table table-condensed">
    <tr>
        <th>Satış Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SatisId</td>
            <td>@item.Urun.UrunAd</td>
            <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
            <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
            <td>@item.Fiyat</td>
            <td>@item.Adet</td>
            <td>@item.ToplamTutar</td>
            <td>@item.Tarih</td>            
        </tr>
    }

</table>
<button class="btn btn-info">Yazdır</button>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Satis/SatisEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Yeni Ürün Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.Urun, "Ürün Adı")
    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Cariler, "Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel, "Personel")
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet, "Adet")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat, "Fiyat")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar, "Toplam Tutar")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-primary">Satış Yap</button>
</form>

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Satış Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    @Html.HiddenFor(x => x.SatisId)
    @Html.LabelFor(x => x.Urun, "Ürün")
    @Html.DropDownListFor(x => x.UrunId, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Cariler, "Cari")
    @Html.DropDownListFor(x => x.CariId, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel, "Personel")
    @Html.DropDownListFor(x => x.PersonelId, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet, "Adet")
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat, "Fiyat")
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar, "Toplam")
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih, "Tarih")
    @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

MvcOnlineTicariOtomasyon/MvcOnlineTicariOtomasyon/Views/Satis/SatisListele.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisListele";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Adet</th>
        <th>Fiyat</th>
        <th>Toplam</th> 
        <th>Tarih</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.SatisId</td>
    <td>@item.Urun.UrunAd</td>
    <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
    <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
    <td>@item.Adet</td>
    <td>@item.Fiyat</td>
    <td>@item.ToplamTutar</td>
    <td>@item.Tarih</td>
    <td><a href="/Satis/SatisGetir/@item.PersonelId" class="btn btn-warning">Güncelle</a></td>
    <td><a href="/Departman/DepartmanPersonelSatis/@item.PersonelId" class="btn btn-secondary">Detaylar</a></td>
</tr>
    }
</table>

<a href="/Satis/SatisEkle" class="btn btn-primary">Yeni Satış Yap</a>